# Generated by Django 5.1.1 on 2024-11-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_profile_delete_userlibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
