# Generated by Django 5.2 on 2025-05-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0004_alter_profile_profile_picture_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
