# Generated by Django 5.1.2 on 2024-11-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_tag_remove_book_book_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingprogress',
            name='book',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='book',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='current_chapter',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='ReadingProgress',
        ),
    ]
