# Generated by Django 5.1.1 on 2024-12-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='book_images/')),
            ],
        ),
    ]
