# Generated by Django 5.1.3 on 2024-11-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
