# Generated by Django 5.1.1 on 2024-11-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_book_isbn_remove_book_summary_book_book_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_image',
        ),
    ]
